import SwiftUI
import SwiftData
import UniformTypeIdentifiers

struct BackupSettingsView: View {

    @Environment(\.appTheme) var theme
    @Environment(\.modelContext) private var ctx

    @Bindable var settings: AppSettings

    @Query private var entries: [DailyEntry]
    @Query private var customVariables: [CustomVariable]

    // IMPORT

    @State private var showingImporter = false
    @State private var previewDates: [String] = []
    @State private var selectedFile: URL?
    @State private var showPreview = false

    @State private var importMode: BackupManager.ImportMode = .merge
    @State private var fromDate = Date()
    @State private var toDate = Date()

    // EXPORT

    @State private var isExporting = false
    @State private var exportError: String?
    @State private var exportSuccess = false

    var body: some View {

        Form {

            // MARK: EXPORT

            Section("Export") {

                Button {
                    runExport()
                } label: {

                    if isExporting {
                        HStack {
                            ProgressView()
                            Text("Preparing export...")
                        }
                    } else {
                        Label(
                            "Export CSV",
                            systemImage: "square.and.arrow.up"
                        )
                        .foregroundStyle(theme.accent)
                    }
                }

                Button {
                    exportTemplate()
                } label: {
                    Label(
                        "Download CSV Template",
                        systemImage: "doc.badge.plus"
                    )
                    .foregroundStyle(theme.accent)
                }

                if let exportError {
                    Text("Error: \(exportError)")
                        .font(.caption)
                        .foregroundStyle(.red)
                }

                if exportSuccess {
                    Text("✅ Export ready")
                        .font(.caption)
                        .foregroundStyle(.green)
                }
            }
            .listRowBackground(theme.card)

            // MARK: IMPORT

            Section("Import") {

                Button {
                    showingImporter = true
                } label: {
                    Label(
                        "Import CSV",
                        systemImage: "square.and.arrow.down"
                    )
                    .foregroundStyle(theme.accent)
                }

                Text("""
Import a CSV generated by this app or use the template as a guide.
""")
                .font(.caption)
                .foregroundStyle(theme.secondary)
            }
            .listRowBackground(theme.card)
        }

        .scrollContentBackground(.hidden)
        .background(theme.bg.ignoresSafeArea())
        .navigationTitle("Backup & Export")

        .fileImporter(
            isPresented: $showingImporter,
            allowedContentTypes: [UTType.commaSeparatedText],
            allowsMultipleSelection: false
        ) { result in
            handleImport(result)
        }

        .sheet(isPresented: $showPreview) {

            VStack(spacing: 20) {

                CSVPreview(dates: previewDates)

                Picker(
                    "Mode",
                    selection: $importMode
                ) {

                    Text("Merge")
                        .tag(BackupManager.ImportMode.merge)

                    Text("Replace")
                        .tag(BackupManager.ImportMode.replace)
                }
                .pickerStyle(.segmented)

                VStack {

                    DatePicker(
                        "From",
                        selection: $fromDate,
                        displayedComponents: .date
                    )

                    DatePicker(
                        "To",
                        selection: $toDate,
                        displayedComponents: .date
                    )
                }

                Button("Confirm Import") {
                    confirmImport()
                }
                .buttonStyle(.borderedProminent)

                Button("Cancel") {
                    showPreview = false
                }
            }
            .padding()
        }
    }

    // MARK: EXPORT

    private func runExport() {

        isExporting = true
        exportError = nil
        exportSuccess = false

        Task {

            do {

                try await BackupManager.shared.runBackup(
                    entries: entries,
                    customVariables: customVariables,
                    settings: settings,
                    presentingViewController: nil
                )

                exportSuccess = true

            } catch BackupManager.BackupError.noEntries {

                exportError = "No data to export"

            } catch {

                exportError = error.localizedDescription
            }

            isExporting = false
        }
    }

    // MARK: TEMPLATE

    private func exportTemplate() {

        Task {

            do {

                try await BackupManager.shared.exportTemplateCSV()

            } catch {

                exportError = error.localizedDescription
            }
        }
    }

    // MARK: IMPORT

    private func handleImport(_ result: Result<[URL], Error>) {

        previewDates = []
        selectedFile = nil

        do {

            let urls = try result.get()

            guard let url = urls.first else {
                return
            }

            selectedFile = url

            previewDates =
                try BackupManager.shared.previewCSV(
                    from: url
                )

            if let first = previewDates.first,
               let last = previewDates.last,
               let d1 = Date.from(isoDate: first),
               let d2 = Date.from(isoDate: last) {

                fromDate = d1
                toDate = d2
            }

            showPreview = true

        } catch {

            print("Import error:", error)
        }
    }

    private func confirmImport() {

        guard let file = selectedFile else {
            return
        }

        do {

            try BackupManager.shared.importCSV(
                from: file,
                context: ctx,
                mode: importMode,
                dateRange: fromDate...toDate
            )

            showPreview = false

        } catch {

            print("Import failed:", error)
        }
    }
}
